services:

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: agriculture
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 1234
    ports:
      - 7000:7000
    networks:
      - ag

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8004:8003
    volumes:
      - ./app:/app
    networks:
      - ag

networks:
    ag:
      external: true

