"""empty message

Revision ID: 7a497025eebc
Revises: 
Create Date: 2024-09-30 02:31:40.362730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a497025eebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                            sa.Column('tipo', sa.String(length=50), nullable=True),
                            sa.Column('areaCultivada', sa.Float(), nullable=False),
                            sa.Column('fechaSiembra', sa.String(length=20), nullable=False),
                            sa.Column('fechaCosecha', sa.String(length=20), nullable=False),
                            sa.PrimaryKeyConstraint('id')
                            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
